version: '3.8'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "7500:7500"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./vuepage/dist:/var/www/vuepage/dist
    depends_on:
      - app
      - db
    networks:
      - app-network

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  app:
    container_name: blog
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
